### PR TITLE
Change from HLS Links for Computer to HLS Links for ChromeCast

### PR DESCRIPTION
**Pull request by kaileu**
As mentioned here https://github.com/aqw/xbmc-gamepass/issues/306 there is a Quality Setting Missing

### CODE REVIEW

**Comment by BaumSchorle** [comment]
Does this result in Higher bitrate being offered? Did you test it with a few games/shows?

**Comment by kaileu** [comment]
Yes it does its a 6k Bitrate.
I have testet it on NFL Live, a few games (full, condensed) and a few shows.

**Comment by BaumSchorle** [comment]
Ok, I am going to merge this!

**Comment by aqw** [comment]
@kaileu Nice find. Thanks for the patch; and thanks @BaumSchorle for merging. :-)

---Alex

**Comment by chovy** [comment]
Is it still an m3u8 file? or what is chromecast format?

**Comment by aqw** [comment]
@chovy I havn't reviewed the changes closely, but I assume it's still m3u8, just delivered with different codecs.

---Alex

**Comment by aqw** [comment]
@chovy Ahem... after reviewing the one-liner change, I can safely say: yep, it's still all m3u8. ;-)

---Alex

**Pull request merged**
