### PR TITLE
Choose Streaming Format

### PR DESCRIPTION
**Pull request by kaileu**
Add the ability to choose a Streaming Format HLS/ChromeCast/ConnectedTV is supported

### CODE REVIEW

**Comment by aqw** [comment]
@kaileu Can you list the advantages of the different formats? I was out of town for two days, but skimming through the issue threads, it seems like Chromecast is the best. Or is there a reason to use other stream types?

---Alex

**Comment by kaileu** [comment]
HLS was the Standard Format maily used for PC but it has not all Qualities and causes Codec Problems
ChromeCast (which we added today) has more Qualitys to Chose from and it seems that it causes less Codec Issues
ISS uses a whole diffrent manifest
ConnectedTV seems to be AirPlay


This commit is more elegant because the Format isn't fixed and you can Change it if you want to.
I think ist more elegant as a fixed coded one.

**Comment by aqw** [comment]
@kaileu more flexible is not always better. ;-)

First off, if indeed ISS uses a completely different manifest, it shouldn't be an option, since we can't parse it.

If "Chromecast HLS" is better than "Computer HLS", then we should simply use Chromecast HLS. I don't see much advantage to giving users the option to degrade their experience, have problems, and open more bug reports. ;-)

As for AirPlay, I don't know anything about that, so I have no idea if it would be relevant to us.

I appreciate the PR, I just want to make sure this will actually be useful.

---Alex

**Comment by kaileu** [comment]
i think its usefull because  if it happen that one Game didn't offer ChromeCast Stream it won't work. (i hope it will but not enough experience)
So its possible to try a diffrent one.
Its Default ist ChromeCast so just in case to Switch fast between the avaiable Streams.

**Comment by aqw** [comment]
@kaileu Ehhhh. The hypothetical that they might possibly not offer a given game in all stream formats is a bit weak for me. I can maybe... maybe see having this behind an "advanced" config mode, or, if they ever do have problems, using "Computer" as an auto-fallback when "Chromecast" fails. But with no history of any streams failing like this, it seems odd to add that fallback.

As for the other to stream types, right now they seem to me as distinct anti-features.

---Alex

**Comment by aqw** [comment]
@kaileu I'm going to close this PR as I'm not convinced it will be beneficial. If we have a need later, we can use it as a starting point.

Thanks for taking the time and effort to make a PR though. :-)

---Alex

**Pull request closed without merging**
