### PR TITLE
Cleanup and fix game versions acquisition

### PR DESCRIPTION
**Pull request by emilsvennesson**
This code was in need of a major overhaul. Game Pass just added the 2014 and 2015 season, but they only have the games available in condensed version right now -- which causes our current logic to fail.

Note: I changed the default game version preference from 'Full' to 'Ask'.

### CODE REVIEW

**Comment by kaileu** [comment]
Works nice great Job!

**Comment by aqw** [comment]
@emilsvennesson Fantastic. Pretty much everything grew very... organically. So there's a lot of janky code that needs cleanup or only made sense with the old service. ;-)

One question: has this been tested against live games as well? I think I saw that you removed all checking for "live" (which NeuLion would deliver with alternate servers and fully encrypted).

 I don't have time over the next two days to do a full review of this, but you've been submitting good stuff and @kaileu has given a thumbs up. So if you answer the above concern, and I'll just merge it straightaway.

---Alex

**Comment by kaileu** [comment]
On my live i tested it works:)

Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment]
@kaileu Excellent. Thanks for testing.

@emilsvennesson will merge shortly.

---Alex

**Comment by emilsvennesson** [comment]
@aqw Thanks! FYI, we're supplying the video ID directly if a game is determined as live as they don't have any game versions available. See line 187 in default.py. :-)

**Comment by aqw** [comment]
@emilsvennesson Excellent. Thanks for clarifying. :-)

**Pull request closed without merging**
