### PR TITLE
Adding Thumbnails to Episodes

### PR DESCRIPTION
**Pull request by kaileu**
I post the PR but i would still hold it back because most of the episodes did not provide Thumbnails at the moment

### CODE REVIEW

**Comment by aqw** [comment]
@kaileu Ok. We'll let this sit here as a reminder until more of the thumbnails show up.

**Comment by kaileu** [comment]
I added a 2nd Solution.
More Network Traffic but all Shows Thumbnails

**Comment by aqw** [comment]
@kaileu Do you feel this is ready for inclusion yet? Or do you still want to wait?

---Alex

**Comment by kaileu** [comment]
Its ready but needs a bit more traffic but its complete.
If a cleaner solution will be available in the future we can change the method.

**Pull request closed without merging**
