### PR TITLE
Fix get_weeks_games()

### LINKED ISSUE #330: Archived Games won't playing anymore
[kodilog.txt](https://github.com/aqw/xbmc-gamepass/files/1242534/kodilog.txt)

 
I receive an error message every time I try to start an archived game. Nfl Network runs without problems.

### PR DESCRIPTION
**Pull request by emilsvennesson**
Fixes #330.

We should probably push out a new release with this fix included seeing as a lot of stuff has stopped working.

### CODE REVIEW

**Comment by aqw** [comment]
@emilsvennesson Thanks again. :-)

**Comment by aqw** [comment]
@emilsvennesson You've been doing a lot of good work recently. The code is nice, you've been responsive to changes, and you've been reviewing the patches of others. Would you be interested in having commit access?

As always, the usual thing about Great Power and Great Responsibility, but I think this would be a good thing. :-) Interested?

---Alex

**Comment by emilsvennesson** [comment]
@aqw That would interest me indeed! It'd be nice and conventional not having to go through the PR route every time.

Thank you for the kind words. :-)

**Comment by aqw** [comment]
@emilsvennesson Excellent. Invitation sent. :-) Key expectations are: 

- you break it, you fix it
- commits should be clean and logically separate
- tip of master should be kept in a working state.

That about sums it up.

Thanks again for helping out. :-)

---Alex

**Comment by emilsvennesson** [comment]
Those are all reasonable expectations. :)

Thanks!

**Pull request closed without merging**
