### PR TITLE
Initial Commit for the new nfl backend

### PR DESCRIPTION
**Pull request by kaileu**
working features:
	archived broadcast
	archived condensed
	archived coaches (like the other not in the special ui)
        NFL Network 24x7
not working at the moment:
	live games (may work or not we will see)
	nfl network archive as a whole
	specific Bitrates from settings
toDo:
reactivate ssl verification

### CODE REVIEW

**Comment by aqw** [comment]
@kaileu Holy hell. I spend an evening away from the computer. I come back the next day and you've rewritten half the addon! :-D

Great to see so much progress. Really very impressive, and encouraging.

I don't have the time right this moment to review, but I'll see if I can make enough progress at work to carve out an hour or two later to look at this.

Thanks for your (considerable) efforts on this.

---Alex

**Comment by emilsvennesson** [comment]
@kaileu Nice job! It'd be nice to have this merged so I could start helping out without merge conflicts.

**Comment by kaileu** [comment]
Yeah i am getting a bit more comfortable with Python the last 2 days :-P

**Comment by kaileu** [comment]
As for now i think we are feature complete.
not working at the moment:
live games (may work or not we will see but i think it will work)
specific Bitrates from settings there is a bug in my code but i didn't find it^^ 
RedZone Archive: There is no Redzone at the moment

toDO:
remove verify=False  in requests

**Comment by aqw** [comment]
Hey @kaileu 

I just wanted to hop on real quick and say: wow. It looks like you've made a lot of progress.

I'm hoping to set aside some time in the next day or so to review this. If I don't review this by Tuesday evening, feel free to ping me and I'll get back to you.

Thanks again!

---Alex

**Comment by aqw** [comment]
@kaileu Merged. Great work!

I have put together a list in #294 of where we go from here.

---Alex

**Pull request closed without merging**
